# Generated by Django 6.0.7 on 2026-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNIQUE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.CharField(blank=True, choices=[('General Medicine', 'General Medicine'), ('Emergency Care', 'Emergency Care'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory'), ('Family Care', 'Family Care'), ('Specialist Care', 'Specialist Care')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
